/***
  Copyright 2018 J. West
 */
#ifndef HOMEWORK07_INCLUDE_HOMEWORK07_SOLVER_H_
#define HOMEWORK07_INCLUDE_HOMEWORK07_SOLVER_H_

class Solver {
};

#endif  // HOMEWORK07_INCLUDE_HOMEWORK07_SOLVER_H_
