/***
  Copyright 2018 J. West
 */
#ifndef HOMEWORK00_INCLUDE_HOMEWORK00_HOMEWORK00_H_
#define HOMEWORK00_INCLUDE_HOMEWORK00_HOMEWORK00_H_
double squareRoot(const double a);
#endif  // HOMEWORK00_INCLUDE_HOMEWORK00_HOMEWORK00_H_
